# bridge
# Autogenerated from man page /usr/share/man/man8/bridge.8.gz
complete -c bridge -s V -o Version --description 'print the version of the  bridge utility and exit.'
complete -c bridge -s s --description 'bridge link set dev DEV  [  cost COST  ] [  priority PRIO  ]  [  state STATE …'
complete -c bridge -o stats -o statistics --description 'output more information.'
complete -c bridge -o details --description 'option, the command becomes verbose.'

