# cfdisk
# Autogenerated from man page /usr/share/man/man8/cfdisk.8.gz
complete -c cfdisk -s a --description 'Use an arrow cursor instead of reverse video for highlighting the current par…'
complete -c cfdisk -s g --description 'Do not use the geometry given by the disk driver, but try to guess a geometry…'
complete -c cfdisk -s v --description 'Print the version number and copyright.'
complete -c cfdisk -s z --description 'Start with zeroed partition table.'
complete -c cfdisk -s s --description 'Override the number of cylinders, heads and sectors per track read from the B…'
complete -c cfdisk -s c --description '.'
complete -c cfdisk -s h --description '.'
complete -c cfdisk -s P --description 'Prints the partition table in specified formats.'

