# chage
# Autogenerated from man page /usr/share/man/man1/chage.1.gz
complete -c chage -s d -l lastday --description 'Set the number of days since January 1st, 1970 when the password was last cha…'
complete -c chage -s E -l expiredate --description 'Set the date or number of days since January 1, 1970 on which the user\\*(Aqs …'
complete -c chage -s h -l help --description 'Display help message and exit.'
complete -c chage -s I -l inactive --description 'Set the number of days of inactivity after a password has expired before the …'
complete -c chage -s l -l list --description 'Show account aging information.'
complete -c chage -s m -l mindays --description 'Set the minimum number of days between password changes to MIN_DAYS.'
complete -c chage -s M -l maxdays --description 'Set the maximum number of days during which a password is valid.'
complete -c chage -s R -l root --description 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c chage -s W -l warndays --description 'Set the number of days of warning before a password change is required.'
complete -c chage -s 1 --description 'as the EXPIRE_DATE will remove an account expiration date.'

