# chardet
# Autogenerated from man page /usr/share/man/man1/chardet.1.gz
complete -c chardet -s h -l help --description 'show this help message and exit SEE ALSO /usr/share/doc/python-chardet/index.'

