# dirname
# Autogenerated from man page /usr/share/man/man1/dirname.1.gz
complete -c dirname -s z -l zero --description 'separate output with NUL rather than newline.'
complete -c dirname -l help --description 'display this help and exit.'
complete -c dirname -l version --description 'output version information and exit EXAMPLES.'
complete -c dirname -s '>' --description '.'

