# fsfreeze
# Autogenerated from man page /usr/share/man/man8/fsfreeze.8.gz
complete -c fsfreeze -s h -l help --description 'Print help and exit.'
complete -c fsfreeze -s f -l freeze --description 'This option requests the specified a filesystem to be frozen from new modific…'
complete -c fsfreeze -s u -l unfreeze --description 'This option is used to un-freeze the filesystem and allow operations to conti…'

