# fstrim
# Autogenerated from man page /usr/share/man/man8/fstrim.8.gz
complete -c fstrim -s h -l help --description 'Print help and exit.'
complete -c fstrim -s o -l offset --description 'Byte offset in filesystem from which to begin searching for free blocks to di…'
complete -c fstrim -s l -l length --description 'Number of bytes after starting point to search for free blocks to discard.'
complete -c fstrim -s m -l minimum --description 'Minimum contiguous free range to discard, in bytes.'
complete -c fstrim -s v -l verbose --description 'Verbose execution.'

