# fstrim-all
# Autogenerated from man page /usr/share/man/man8/fstrim-all.8.gz
complete -c fstrim-all -l no-model-check --description 'option to disable the vendor check and run fstrim on all SSD drives.'

