# gendsa
# Autogenerated from man page /usr/share/man/man1/gendsa.1ssl.gz
complete -c gendsa -o des -o des3 -o idea --description 'These options encrypt the private key with the \\s-1DES,\\s0 triple \\s-1DES,\\s0…'
complete -c gendsa -o rand --description 'a file or files containing random data used to seed the random number generat…'
complete -c gendsa -o engine --description 'specifying an engine (by its unique id string) will cause gendsa to attempt t…'

