# git-for-each-ref
# Autogenerated from man page /usr/share/man/man1/git-for-each-ref.1.gz
complete -c git-for-each-ref -l shell -l perl -l python -l tcl --description 'If given, strings that substitute %(fieldname) placeholders are quoted as str…'
complete -c git-for-each-ref -l format --description 'Subject: %(*subject) Date: %(*authordate) Ref: %(*refname).'

