# git-reflog
# Autogenerated from man page /usr/share/man/man1/git-reflog.1.gz
complete -c git-reflog -l stale-fix --description 'This revamps the logic \\(em the definition of "broken commit" becomes: a comm…'
complete -c git-reflog -l expire --description 'Entries older than this time are pruned.'
complete -c git-reflog -l expire-unreachable --description 'Entries older than this time and not reachable from the current tip of the br…'
complete -c git-reflog -l all --description 'Instead of listing <refs> explicitly, prune all refs.'
complete -c git-reflog -l updateref --description 'Update the ref with the sha1 of the top reflog entry (i. e.'
complete -c git-reflog -l rewrite --description 'While expiring or deleting, adjust each reflog entry to ensure that the old s…'
complete -c git-reflog -l verbose --description 'Print extra information on screen.'

