# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
complete -c halt -s f -l force --description 'Does not invoke  shutdown (8) and instead performs the actual action you woul…'
complete -c halt -s p -l poweroff --description 'Instructs the  halt command to instead behave as  poweroff . \\".'
complete -c halt -s w -l wtmp-only --description 'Does not call  shutdown(8) or the  reboot(2) system call and instead only wri…'
complete -c halt -l verbose --description 'Outputs slightly more verbose messages when rebooting, useful for debugging p…'

