# head
# Autogenerated from man page /usr/share/man/man1/head.1.gz
complete -c head -s c -l bytes --description 'print the first K bytes of each file; with the leading \'-\', print all but the…'
complete -c head -s n -l lines --description 'print the first K lines instead of the first 10; with the leading \'-\', print …'
complete -c head -s q -l quiet -l silent --description 'never print headers giving file names.'
complete -c head -s v -l verbose --description 'always print headers giving file names.'
complete -c head -l help --description 'display this help and exit.'
complete -c head -l version --description 'output version information and exit.'

