# hostnamectl
# Autogenerated from man page /usr/share/man/man1/hostnamectl.1.gz
complete -c hostnamectl -s h -l help --description 'Prints a short help text and exits.'
complete -c hostnamectl -l version --description 'Prints a short version string and exits.'
complete -c hostnamectl -l no-ask-password --description 'Don\\*(Aqt query the user for authentication for privileged operations.'
complete -c hostnamectl -s H -l host --description 'Execute the operation remotely.'
complete -c hostnamectl -l static -l transient -l pretty --description 'If set-hostname is invoked and one or more of these options are passed only t…'

