# init
# Autogenerated from man page /usr/share/man/man8/init.8.gz
complete -c init -l chroot-sessions --description 'Enable chroot session support.  See  Chroot Support in  init (5) "" ". " . \\".'
complete -c init -l confdir --description 'Read job configuration files from a directory other than the default (/etc/in…'
complete -c init -l default-console --description 'Default value for jobs that do not specify a \\(aqconsole\\(aq stanza.'
complete -c init -l no-dbus --description 'Do not connect to a D-Bus bus. \\".'
complete -c init -l no-inherit-env --description 'Stop jobs from inheriting the initial environment.'
complete -c init -l logdir --description 'Write job output log files to a directory other than /var/log/upstart (system…'
complete -c init -l no-log --description 'Disable logging of job output.'
complete -c init -l no-sessions --description 'Disable chroot sessions (default). \\".'
complete -c init -l no-startup-event --description 'Suppress emission of the initial startup event.'
complete -c init -l session --description 'Connect to the D-Bus session bus.  This should only be used for testing. \\".'
complete -c init -l startup-event --description 'Specify a different initial startup event from the standard  startup (7) . \\".'
complete -c init -l user --description 'Starts in user mode, as used for user sessions.'
complete -c init -s q -l quiet --description 'Reduces output messages to errors only. \\".'
complete -c init -s v -l verbose --description 'Outputs verbose messages about job state changes and event emissions to the s…'
complete -c init -l version --description 'Outputs version information and exits.'

