# ip-link
# Autogenerated from man page /usr/share/man/man8/ip-link.8.gz
complete -c ip-link -s V --description '.'
complete -c ip-link -s s --description '.'
complete -c ip-link -s r --description '.'
complete -c ip-link -s f --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-link -s o --description 'ip link add [  link DEVICE  ] [  name  ] NAME.'

