# ipcs
# Autogenerated from man page /usr/share/man/man1/ipcs.1.gz
complete -c ipcs -s m --description 'shared memory segments.'
complete -c ipcs -s q --description 'message queues.'
complete -c ipcs -s s --description 'semaphore arrays.'
complete -c ipcs -s a --description 'all (this is the default) . PP The output format may be specified as follows:.'
complete -c ipcs -s t --description 'time.'
complete -c ipcs -s p --description 'pid.'
complete -c ipcs -s c --description 'creator.'
complete -c ipcs -s l --description 'limits.'
complete -c ipcs -s i --description 'option allows a specific resource id to be specified.'
complete -c ipcs -s u --description 'summary SEE ALSO ipcrm (1), ipcmk (1) CONFORMING TO The Linux ipcs utility is…'
complete -c ipcs -s b --description 'and.'
complete -c ipcs -s o --description 'options, but does support the.'

