# irqbalance
# Autogenerated from man page /usr/share/man/man1/irqbalance.1.gz
complete -c irqbalance -l oneshot --description 'Causes irqbalance to be run once, after which the daemon exits.'
complete -c irqbalance -l debug --description 'Causes irqbalance to print extra debug information.   Implies --foreground.'
complete -c irqbalance -l foreground --description 'Causes irqbalance to run in the foreground (without --debug).'
complete -c irqbalance -l hintpolicy --description 'Set the policy for how irq kernel affinity hinting is treated.'
complete -c irqbalance -l powerthresh --description 'Set the threshold at which we attempt to move a cpu into powersave mode If mo…'
complete -c irqbalance -l banirq --description 'Add the specified irq to the set of banned irqs.'
complete -c irqbalance -l policyscript --description 'When specified, the referenced script will execute once for each discovered i…'
complete -c irqbalance -l pid --description 'Have irqbalance write its process id to the specified file.'

