# landscape-client
# Autogenerated from man page /usr/share/man/man1/landscape-client.1.gz
complete -c landscape-client -l version --description 'Show program\'s version number and exit.'
complete -c landscape-client -s h -l help --description 'Show this help message and exit.'
complete -c landscape-client -s c -l config --description 'Use config from this file (any command line  options override settings from t…'
complete -c landscape-client -s d -l data-path --description 'The directory to store data files in (default: \'/var/lib/landscape/client/\').'
complete -c landscape-client -s q -l quiet --description 'Do not log to the standard output.'
complete -c landscape-client -s l -l log-dir --description 'The directory to write log files to (default: \'/var/log/landscape\').'
complete -c landscape-client -l log-level --description 'One of debug, info, warning, error or critical.'
complete -c landscape-client -s u -l url --description 'The server URL to connect to.'
complete -c landscape-client -l ping-url --description 'The URL to perform lightweight exchange initiation with.'
complete -c landscape-client -s k -l ssl-public-key --description 'The public SSL key to  verify the server.'
complete -c landscape-client -l ignore-sigint --description 'Ignore interrupt signals.'
complete -c landscape-client -l ignore-sigusr1 --description 'Ignore SIGUSR1 signal to rotate logs.'
complete -c landscape-client -l daemon --description 'Fork and run in the background.'
complete -c landscape-client -l pid-file --description 'The file to write the PID to.'
complete -c landscape-client -l monitor-only --description 'Don\'t enable management features.'

