# ld-linux
# Autogenerated from man page /usr/share/man/man8/ld-linux.8.gz
complete -c ld-linux -l list --description 'List all dependencies and how they are resolved.'
complete -c ld-linux -l verify --description 'Verify that program is dynamically linked and this dynamic linker can handle …'
complete -c ld-linux -l library-path --description 'Use PATH instead of  LD_LIBRARY_PATH environment variable setting (see below).'
complete -c ld-linux -l inhibit-rpath --description 'Ignore RPATH and RUNPATH information in object names in LIST.'
complete -c ld-linux -o static --description 'option was given to ld (1) during compilation.'
complete -c ld-linux -s z --description 'linker option, libraries in the default library paths are skipped.'
complete -c ld-linux -l audit --description 'Use objects named in LIST as auditors.'

