# ldd
# Autogenerated from man page /usr/share/man/man1/ldd.1.gz
complete -c ldd -l version --description 'Print the version number of  ldd .'
complete -c ldd -o v--verbose --description 'Print all information, including, for example, symbol versioning information.'
complete -c ldd -o u--unused --description 'Print unused direct dependencies.  (Since glibc 2. 3. 4. ).'
complete -c ldd -o d--data-relocs --description 'Perform relocations and report any missing objects (ELF only).'
complete -c ldd -o r--function-relocs --description 'Perform relocations for both data objects and functions, and report any missi…'
complete -c ldd -s v -l verbose --description 'Print all information, including, for example, symbol versioning information.'
complete -c ldd -s u -l unused --description 'Print unused direct dependencies.  (Since glibc 2. 3. 4. ).'
complete -c ldd -s d -l data-relocs --description 'Perform relocations and report any missing objects (ELF only).'
complete -c ldd -s r -l function-relocs --description 'Perform relocations for both data objects and functions, and report any missi…'
complete -c ldd -l help --description 'Usage information.  NOTES The standard version of ldd comes with glibc2.'
complete -c ldd -s V --description 'and only has the equivalent.'

