# locale-gen
# Autogenerated from man page /usr/share/man/man8/locale-gen.8.gz
complete -c locale-gen -l help --description 'Display an help message and exit.'
complete -c locale-gen -l purge --description 'Remove all existing locales before processing.'
complete -c locale-gen -l no-purge --description 'Do not remove existing locales before processing.'
complete -c locale-gen -l archive --description 'When this option is set, locale data are stored in a single archive  /usr/lib…'
complete -c locale-gen -l no-archive --description 'When this option is set, locale data are stored in  /usr/lib/locale/<locale_n…'

