# localectl
# Autogenerated from man page /usr/share/man/man1/localectl.1.gz
complete -c localectl -s h -l help --description 'Prints a short help text and exits.'
complete -c localectl -l version --description 'Prints a short version string and exits.'
complete -c localectl -l no-pager --description 'Do not pipe output into a pager.'
complete -c localectl -l no-ask-password --description 'Don\\*(Aqt query the user for authentication for privileged operations.'
complete -c localectl -s H -l host --description 'Execute the operation remotely.'
complete -c localectl -l no-convert --description 'If set-keymap or set-x11-keymap is invoked and this option is passed then the…'
complete -c localectl -l 'no-pager.' --description '.'

