# loginctl
# Autogenerated from man page /usr/share/man/man1/loginctl.1.gz
complete -c loginctl -s h -l help --description 'Prints a short help text and exits.'
complete -c loginctl -l version --description 'Prints a short version string and exits.'
complete -c loginctl -s p -l property --description 'When showing session/user properties, limit display to certain properties as …'
complete -c loginctl -s a -l all --description 'When showing unit/job/manager properties, show all properties regardless whet…'
complete -c loginctl -l full --description 'Do not ellipsize cgroup members.'
complete -c loginctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c loginctl -l no-ask-password --description 'Don\\*(Aqt query the user for authentication for privileged operations.'
complete -c loginctl -l kill-who --description 'When used with kill-session, choose which processes to kill.'
complete -c loginctl -s s -l signal --description 'When used with kill-session or kill-user, choose which signal to send to sele…'
complete -c loginctl -s H -l host --description 'Execute operation remotely.'
complete -c loginctl -s P -l privileged --description 'Acquire privileges via PolicyKit before executing the operation.'
complete -c loginctl -l 'no-pager.' --description '.'

