# more
# Autogenerated from man page /usr/share/man/man1/more.1.gz
complete -c more -o num --description 'This option specifies an integer which is the screen size (in lines).'
complete -c more -s d --description 'more more will prompt the user with the message "[Press space to continue, \'q…'
complete -c more -s l --description 'more more usually treats \\&^L (form feed) as a special character, and will pa…'
complete -c more -s f --description 'Causes more more to count logical, rather than screen lines (i. e.'
complete -c more -s p --description 'Do not scroll.   Instead, clear the whole screen and then display the text.'
complete -c more -s c --description 'Do not scroll.'
complete -c more -s s --description 'Squeeze multiple blank lines into one.'
complete -c more -s u --description 'Suppress underlining.'

