# partx
# Autogenerated from man page /usr/share/man/man8/partx.8.gz
complete -c partx -s a -l add --description 'Add the specified partitions, or read the disk and add all partitions.'
complete -c partx -s b -l bytes --description 'Print the SIZE column in bytes rather than in human-readable format.'
complete -c partx -s d -l delete --description 'Delete the specified partitions or all partitions.'
complete -c partx -s u -l update --description 'Update the specified partitions.'
complete -c partx -s g -l noheadings --description 'Do not print a header line.'
complete -c partx -s l -l list --description 'List the partitions.   Note that all numbers are in 512-byte sectors.'
complete -c partx -s o -l output --description 'Define the output columns to use for --show and  --raw output.'
complete -c partx -s r -l raw --description 'Use the raw output format.'
complete -c partx -s s -l show --description 'List the partitions.   All numbers (except SIZE) are in 512-byte sectors.'
complete -c partx -s t -l type --description 'Specify the partition table type -- aix, bsd, dos, gpt, mac, minix, sgi, sola…'
complete -c partx -s n -l nr --description 'Specify the range of partitions.'

