# pldd
# Autogenerated from man page /usr/share/man/man1/pldd.1.gz
complete -c pldd -l usage --description 'Give a short usage message.'
complete -c pldd -o V--version --description 'Print the version number of  pldd .'
complete -c pldd -s V -l version --description 'Print the version number of pldd .'
complete -c pldd -s '?' -l help --description 'Usage information.  AUTHOR Ulrich Drepper.  SEE ALSO ldd (8).'

