# raw
# Autogenerated from man page /usr/share/man/man8/raw.8.gz
complete -c raw -s q --description 'Set query mode.'
complete -c raw -s a --description 'With  -q , specify that all bound raw devices should be queried.'
complete -c raw -s h --description 'Provide a usage summary.'

