# readprofile
# Autogenerated from man page /usr/share/man/man1/readprofile.1.gz
complete -c readprofile -s m --description 'Specify a mapfile, which by default is  /usr/src/linux/System. map.'
complete -c readprofile -s p --description 'Specify a different profiling buffer, which by default is  /proc/profile.'
complete -c readprofile -s i --description 'Info.'
complete -c readprofile -s a --description 'Print all symbols in the mapfile.'
complete -c readprofile -s b --description 'Print individual histogram-bin counts.'
complete -c readprofile -s r --description 'Reset the profiling buffer.'
complete -c readprofile -s M --description 'On some architectures it is possible to alter the frequency at which the kern…'
complete -c readprofile -s v --description 'Verbose.  The output is organized in four columns and filled with blanks.'
complete -c readprofile -s t --description '(terse) switch is used together with.'
complete -c readprofile -s V --description 'Version.  This makes readprofile print its version number and exit.'

