# runlevel
# Autogenerated from man page /usr/share/man/man8/runlevel.8.gz
complete -c runlevel -s r --description 'command.'
complete -c runlevel -l quiet --description 'Does not output the current and previous runlevel, nor does it output unknown…'

