# script
# Autogenerated from man page /usr/share/man/man1/script.1.gz
complete -c script -s a --description 'Append the output to file or typescript, retaining the prior contents.'
complete -c script -s c --description 'Run the command rather than an interactive shell.'
complete -c script -s e --description 'Return the exit code of the child process.'
complete -c script -s f --description 'Flush output after each write.'
complete -c script -l force --description 'Allow the default output destination, i. e.'
complete -c script -s q --description 'Be quiet.'
complete -c script -s t --description 'Output timing data to standard error, or to \\fIfile\\fR when given.'
complete -c script -s V --description 'Output version information and exit.'
complete -c script -s h --description 'Output help and exit.'

