# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8.gz
complete -c shutdown -s r --description 'Requests that the system be rebooted after it has been brought down. \\".'
complete -c shutdown -s h --description 'Requests that the system be either halted or powered off after it has been br…'
complete -c shutdown -s H --description 'Requests that the system be halted after it has been brought down. \\".'
complete -c shutdown -s P --description 'Requests that the system be powered off after it has been brought down. \\".'
complete -c shutdown -s c --description 'Cancels a running shutdown.'
complete -c shutdown -s k --description 'Only send out the warning messages and disable logins, do not actually bring …'

