# swapon
# Autogenerated from man page /usr/share/man/man8/swapon.8.gz
complete -c swapon -s a -l all --description 'All devices marked as ``swap\'\' in  /etc/fstab are made available, except for …'
complete -c swapon -s d -l discard --description 'Discard freed swap pages before they are reused, if the swap device supports …'
complete -c swapon -s e -l ifexists --description 'Silently skip devices that do not exist.'
complete -c swapon -s f -l fixpgsz --description 'Reinitialize (exec /sbin/mkswap) the swap space if its page size does not mat…'
complete -c swapon -s h -l help --description 'Provide help.'
complete -c swapon -s L --description 'Use the partition that has the specified R label .'
complete -c swapon -s p -l priority --description 'Specify the priority of the swap device.'
complete -c swapon -s s -l summary --description 'Display swap usage summary by device.  Equivalent to "cat /proc/swaps".'
complete -c swapon -s U --description 'Use the partition that has the specified R uuid .'
complete -c swapon -s v -l verbose --description 'Be verbose.'
complete -c swapon -s V -l version --description 'Display version.  NOTES You should not use swapon on a file with holes.'

