# systemd-udevd-control
# Autogenerated from man page /usr/share/man/man8/systemd-udevd-control.socket.8.gz
complete -c systemd-udevd-control -l daemon --description 'Detach and run in the background.'
complete -c systemd-udevd-control -l debug --description 'Print debug messages to stderr.'
complete -c systemd-udevd-control -l children-max --description 'Limit the number of events executed in parallel.'
complete -c systemd-udevd-control -l exec-delay --description 'Delay the execution of RUN instruction by the given number of seconds.'
complete -c systemd-udevd-control -l resolve-names --description 'Specify when systemd-udevd should resolve names of users and groups.'
complete -c systemd-udevd-control -l version --description 'Print version number.'
complete -c systemd-udevd-control -l help --description 'Print help text.'

