# tail
# Autogenerated from man page /usr/share/man/man1/tail.1.gz
complete -c tail -s c -l bytes --description 'output the last K bytes; alternatively, use -c +K to output bytes starting wi…'
complete -c tail -s f -l follow --description 'output appended data as the file grows; -f, --follow, and --follow=descriptor…'
complete -c tail -s F --description 'same as --follow=name --retry.'
complete -c tail -s n -l lines --description 'output the last K lines, instead of the last 10; or use -n +K to output lines…'
complete -c tail -l max-unchanged-stats --description 'with --follow=name, reopen a FILE which has not changed size after N (default…'
complete -c tail -l pid --description 'with -f, terminate after process ID, PID dies.'
complete -c tail -s q -l quiet -l silent --description 'never output headers giving file names.'
complete -c tail -l retry --description 'keep trying to open a file even when it is or becomes inaccessible; useful wh…'
complete -c tail -s s -l sleep-interval --description 'with -f, sleep for approximately N seconds (default 1. 0) between iterations.'
complete -c tail -s v -l verbose --description 'always output headers giving file names.'
complete -c tail -l help --description 'display this help and exit.'
complete -c tail -l version --description 'output version information and exit.'

