# timedatectl
# Autogenerated from man page /usr/share/man/man1/timedatectl.1.gz
complete -c timedatectl -s h -l help --description 'Prints a short help text and exits.'
complete -c timedatectl -l version --description 'Prints a short version string and exits.'
complete -c timedatectl -l no-pager --description 'Do not pipe output into a pager.'
complete -c timedatectl -l no-ask-password --description 'Don\\*(Aqt query the user for authentication for privileged operations.'
complete -c timedatectl -s H -l host --description 'Execute the operation remotely.'
complete -c timedatectl -l adjust-system-clock --description 'If set-local-rtc is invoked and this option is passed the system clock is syn…'
complete -c timedatectl -l 'no-pager.' --description '.'

