# tunelp
# Autogenerated from man page /usr/share/man/man8/tunelp.8.gz
complete -c tunelp -s i --description 'specifies the IRQ to use for the parallel port in question.'
complete -c tunelp -s t --description 'is the amount of time in jiffies that the driver waits if the printer doesn\'t…'
complete -c tunelp -s c --description 'is the number of times to try to output a character to the printer before sle…'
complete -c tunelp -s w --description 'is the number of usec we wait while playing with the strobe signal.'
complete -c tunelp -s a --description 'This is whether to abort on printer error - the default is not to.'
complete -c tunelp -s o --description 'This option is much like -a.'
complete -c tunelp -s C --description 'This option adds extra ("careful") error checking.'
complete -c tunelp -s s --description 'This option returns the current printer status, both as a decimal number from…'
complete -c tunelp -s T --description 'This option is obsolete.  It was added in Linux 2. 1.'
complete -c tunelp -s r --description 'This option resets the port.   It requires a Linux kernel version of 1. 1.'
complete -c tunelp -s q --description 'This option sets printing the display of the current IRQ setting.  NOTES.'

