# umount
# Autogenerated from man page /usr/share/man/man8/umount.8.gz
complete -c umount -s V --description 'Print version and exit.'
complete -c umount -s h --description 'Print help message and exit.'
complete -c umount -s v --description 'Verbose mode.'
complete -c umount -s n --description 'Unmount without writing in R /etc/mtab .'
complete -c umount -s r --description 'In case unmounting fails, try to remount read-only.'
complete -c umount -s d --description 'In case the unmounted device was a loop device, also free this loop device.'
complete -c umount -s i --description 'Don\'t call the /sbin/umount. <filesystem> helper even if it exists.'
complete -c umount -s a --description 'All of the file systems described in  /etc/mtab are unmounted.'
complete -c umount -s t --description 'Indicate that the actions should only be taken on file systems of the specifi…'
complete -c umount -s O --description 'Indicate that the actions should only be taken on file systems with the speci…'
complete -c umount -s f --description 'Force unmount (in case of an unreachable NFS system).  (Requires kernel 2. 1.'
complete -c umount -s l --description 'Lazy unmount.'
complete -c umount -l no-canonicalize --description 'Don\'t canonicalize paths.'
complete -c umount -l fake --description 'Causes everything to be done except for the actual system call; this ``fakes\'…'

