# uuidd
# Autogenerated from man page /usr/share/man/man8/uuidd.8.gz
complete -c uuidd -s d --description 'Run uuidd in debugging mode.   This prevents uuidd from running as a daemon.'
complete -c uuidd -s h -l help --description 'Display help screen and exit.'
complete -c uuidd -s k -l kill --description 'If currently a uuidd daemon is running, kill it.'
complete -c uuidd -s n -l uuids --description 'When issuing a test request to a running uuidd, request a bulk response of  n…'
complete -c uuidd -s p -l pid --description 'Specify the pathname where the pid file should be written.'
complete -c uuidd -s q --description 'Suppress some failure messages.'
complete -c uuidd -s r -l random --description 'Test uuidd by trying to connect to a running uuidd daemon and request it to r…'
complete -c uuidd -s s -l socket --description 'Specify the pathname used for the unix-domain socket used by uuidd.'
complete -c uuidd -s T -l timeout --description 'Specify a timeout for uuidd.'
complete -c uuidd -s t -l time --description 'Test uuidd by trying to connect to a running uuidd daemon and request it to r…'
complete -c uuidd -s V -l version --description 'Output version information and exit.'

