# wipefs
# Autogenerated from man page /usr/share/man/man8/wipefs.8.gz
complete -c wipefs -s a -l all --description 'Erase all available signatures.'
complete -c wipefs -s h -l help --description 'Print help and exit.'
complete -c wipefs -s n -l no-act --description 'Causes everything to be done except for the write() call.'
complete -c wipefs -s o -l offset --description 'Specify the location (in bytes) of the signature which should be erased from …'
complete -c wipefs -s p -l parsable --description 'Print out in parsable instead of printable format.'
complete -c wipefs -s V -l version --description 'Output version information and exit.  AUTHOR Karel Zak <kzak@redhat. com>.'

